name: spri_explore_1
channels:
  - conda-forge
  - defaults
dependencies:
  - python[version='>=3.8.5']
  - openssl
  - gunicorn[version='>=20.0.4']
  - ld_impl_linux-64[version='>=2.33.1']
  - rq[version='>=1.7.0']
  - flask-migrate[version='>=2.4.0']
  - sqlite[version='>=3.33.0']
  - flask-marshmallow[version='>=0.14.0']
  - flask[version='>=1.1.2']
  - marshmallow-sqlalchemy[version='>=0.24.1']
  - flask-login[version='>=0.5.0']
  - bokeh=2.4.3
  - cycler[version='>=0.10.0']
  - flask-restful[version='>=0.3.8']
  - numpy[version='>=1.18.1']
  - cartopy[version='>=0.18.0']
  - pandas[version='>=1.1.4']
  - marshmallow[version='>=3.10.0']
  - werkzeug[version='<3.0.0'] # Version 3.0 removes support for sha256 password hashes in a way that completely breaks login
  - sqlalchemy
  - flask-sqlalchemy
  - zstd[version='>=1.4.5']
  - email-validator[version='>=1.1.2']
  - yaml[version='>=0.2.5']
  - python-dotenv[version='>=0.15.0']
  - pyyaml[version='>=5.4.1']
  - flask-apscheduler[version='>=1.11.0']
  - flask-caching[version='>=1.7.1']
  - apscheduler[version='>=3.6.3']
  - flask-wtf[version='>=0.14.3']
  - pyepsg
  - psycopg2
  - pip
  - pip:
    - accumulation-tree>=0.6.2
    - flask-talisman>=1.0.0
    - pybrake>=1.10.0
    - pyqt5-sip>=4.19.18
    - pyqtchart>=5.12
    - pyqtwebengine>=5.12.1
    - pyudorandom>=1.0.0
    - sqlalchemy-continuum
    - sqlalchemy-utils
    - tdigest>=0.5.2.2
